# frozen_string_literal: true

require "unitsdb"

module Unitsml
  module Opal
    class PayloadGenerator
      DEFAULT_OUTPUT_PATH =
        File.expand_path("database_payload.rb", __dir__).freeze

      def initialize(unitsdb_data_dir: default_data_dir)
        @unitsdb_data_dir = unitsdb_data_dir
      end

      def call
        "#{header}#{body}"
      end

      def write_to(path = DEFAULT_OUTPUT_PATH)
        File.write(path, call)
        path
      end

      private

      attr_reader :unitsdb_data_dir

      def header
        <<~RUBY
          # frozen_string_literal: true

          # AUTO-GENERATED by `bundle exec rake unitsml:generate_opal_payload`.
          # Do not edit by hand. Edit the YAML in unitsdb-ruby/data/ and
          # regenerate. This file is loaded by lib/unitsml/opal.rb under Opal
          # to satisfy Unitsml::Unitsdb::Database.from_db without a filesystem.
        RUBY
      end

      def body
        "Unitsml::Unitsdb::Database.const_set(:DATABASE, " \
          "#{database_hash.inspect}.freeze)\n"
      end

      def database_hash
        ::Unitsdb::Database.from_db(unitsdb_data_dir).to_hash
      end

      def default_data_dir
        File.join(unitsdb_gem_path, "data")
      end

      def unitsdb_gem_path
        Gem.loaded_specs.fetch("unitsdb").full_gem_path
      end
    end
  end
end
