# frozen_string_literal: true

require "unitsdb"

module Unitsml
  module Opal
    class PayloadGenerator
      DEFAULT_OUTPUT_PATH =
        File.expand_path("database_payload.rb", __dir__).freeze

      RECEIVER = "Unitsml::Unitsdb::Database"
      METHOD = "load_opal_payload"

      # Maps a scalar value's class to the serializer that emits its
      # Ruby source representation. Kept as a constant so adding a new
      # scalar type is a one-line change (OCP).
      SCALAR_SERIALIZERS = {
        String => :inspect.to_proc,
        Symbol => ->(v) { ":#{v}" },
        Integer => :to_s.to_proc,
        Float => :to_s.to_proc,
      }.freeze

      def initialize(unitsdb_data_dir: default_data_dir)
        @unitsdb_data_dir = unitsdb_data_dir
      end

      def call
        "#{header}#{body}"
      end

      def write_to(path = DEFAULT_OUTPUT_PATH)
        File.write(path, call)
        path
      end

      private

      attr_reader :unitsdb_data_dir

      def header
        <<~RUBY
          # frozen_string_literal: true

          # AUTO-GENERATED by `bundle exec rake unitsml:generate_opal_payload`.
          # Do not edit by hand. Edit the YAML in unitsdb-ruby/data/ and
          # regenerate. This file is loaded by lib/unitsml/opal.rb under Opal
          # to satisfy Unitsml::Unitsdb::Database.from_db without a filesystem.
        RUBY
      end

      def body
        "#{RECEIVER}.#{METHOD}(#{serialize(database_hash)}.freeze)\n"
      end

      def database_hash
        ::Unitsdb::Database.from_db(unitsdb_data_dir).to_hash
      end

      # Custom serializer rather than Hash#inspect so the output is
      # byte-identical across Ruby versions (3.3 vs 3.4 changed Hash#inspect
      # to add spaces around "=>"). String#inspect is itself stable for
      # UTF-8 clean data.
      def serialize(value)
        case value
        when Hash then serialize_hash(value)
        when Array then serialize_array(value)
        when true then "true"
        when false then "false"
        when nil then "nil"
        else serialize_scalar(value)
        end
      end

      def serialize_hash(value)
        "{#{value.map { |k, v| "#{serialize(k)}=>#{serialize(v)}" }.join(',')}}"
      end

      def serialize_array(value)
        "[#{value.map { |v| serialize(v) }.join(',')}]"
      end

      def serialize_scalar(value)
        serializer = SCALAR_SERIALIZERS[value.class]
        return serializer.call(value) if serializer

        raise Unitsml::Errors::UnsupportedPayloadTypeError, value.class
      end

      def default_data_dir
        File.join(unitsdb_gem_path, "data")
      end

      def unitsdb_gem_path
        Gem.loaded_specs.fetch("unitsdb").full_gem_path
      end
    end
  end
end
