name: release

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'skip'
      post_install:
        description: 'comamnd to execute after bundle install'
        required: false
        type: string
        default: 'git submodule update --remote --recursive'
  repository_dispatch:
    types: [ do-release ]

jobs:
  release:
    uses: metanorma/ci/.github/workflows/rubygems-release.yml@main
    with:
      next_version: ${{ github.event.inputs.next_version }}
    secrets:
      rubygems-api-key: ${{ secrets.UNITSML_CI_RUBYGEMS_API_KEY }}
